apiVersion: v1
kind: Service
metadata:
  name: booking
  namespace: booking-platform
spec:
  type: NodePort
  selector:
    app: booking
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30080
