networks:
  app-tier:
    driver: bridge

services:

  booking-expiry-worker:
    build:
      context: ..
      dockerfile: packages/booking-expiry-worker/Dockerfile
    env_file:
      - ./.env.production
    networks:
      - app-tier
    depends_on: 
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  campaign-worker:
    build:
      context: ..
      dockerfile: packages/campaign-worker/Dockerfile
    env_file:
      - ./.env.production
    networks:
      - app-tier
    depends_on: 
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  audit-worker:
    build:
      context: ..
      dockerfile: packages/audit-worker/Dockerfile
    env_file:
      - ./.env.production
    networks:
      - app-tier
    depends_on: 
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  
  seller-notification-worker:
    build:
      context: ..
      dockerfile: packages/seller-notification-worker/Dockerfile
    env_file:
      - ./.env.production
    networks:
      - app-tier
    depends_on: 
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  csv-room-import-worker:
    build:
      context: ..
      dockerfile: packages/csv-room-import-worker/Dockerfile
    env_file:
      - ./.env.production
    networks:
      - app-tier
    depends_on: 
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  availability-worker:
    build:
      context: ..
      dockerfile: packages/availability-worker/Dockerfile
    env_file:
      - ./.env.production
    networks:
      - app-tier
    depends_on: 
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  property-search-worker:
    build:
      context: ..
      dockerfile: packages/property-search-worker/Dockerfile
    env_file:
      - ./.env.production
    networks:
      - app-tier
    depends_on: 
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy