networks:
  app-tier:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    networks:
      - app-tier
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    env_file:
      - ./.env.production
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 1m30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    image: redis:7.0-alpine
    container_name: redis
    env_file:
      - ./.env.production
    networks:
      - app-tier
    command: redis-server /etc/redis/redis.conf --save ""
    volumes:
      - redis-data:/data
      - ./_infra/redis/redis.conf:/etc/redis/redis.conf:ro
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
          
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    networks:
      - app-tier
    env_file:
      - ./.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "127.0.0.1:8001:8001"
    networks:
      - app-tier
    volumes:
      - redis-insight-data:/db
    restart: unless-stopped

  booking:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: booking
    env_file:
      - ./.env.production
    networks:
      - app-tier
    ports:
      - "4000:4000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 60s

  booking-expiry-worker:
    build:
      context: ..
      dockerfile: packages/booking-expiry-worker/Dockerfile
    env_file:
      - ./.env.production
    networks:
      - app-tier
    depends_on: 
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  csv-room-import-worker:
    build:
      context: ..
      dockerfile: packages/csv-room-import-worker/Dockerfile
    env_file:
      - ./.env.production
    networks:
      - app-tier
    depends_on: 
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  availability-worker:
    build:
      context: ..
      dockerfile: packages/availability-worker/Dockerfile
    env_file:
      - ./.env.production
    networks:
      - app-tier
    depends_on: 
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #   ports:
  #     - "127.0.0.1:9090:9090"
  #   volumes:
  #     - ./_infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #     - prom_data:/prometheus
  #   networks:
  #     - app-tier

  # loki:
  #   image: grafana/loki:latest
  #   ports:
  #     - "127.0.0.1:3100:3100"
  #   volumes:
  #     - loki_data:/loki
  #     - ./_infra/etc/loki/loki-config.yml:/etc/loki/loki-config.yml
  #   command: -config.file=/etc/loki/loki-config.yml -config.expand-env=true
  #   networks:
  #     - app-tier

  # promtail:
  #   image: grafana/promtail:latest
  #   command: -config.file=/etc/promtail/promtail-config.yml
  #   networks:
  #     - app-tier
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./_infra/etc/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   env_file:
  #     - ./.env.production
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
  #     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
  #     - GF_AUTH_ANONYMOUS_ENABLED=false
  #     - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
  #     - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
  #   entrypoint:
  #     - sh
  #     - -euc
  #     - |
  #       mkdir -p /etc/grafana/provisioning/datasources
  #       cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
  #       apiVersion: 1
  #       datasources:
  #       - name: Loki
  #         type: loki
  #         access: proxy
  #         orgId: 1
  #         url: http://loki:3100
  #         basicAuth: false
  #         isDefault: true
  #         version: 1
  #         editable: false
  #       EOF
  #       /run.sh
  #   ports:
  #     - "127.0.0.1:3000:3000"
  #   volumes:
  #     - ./_infra/grafana.ini:/etc/grafana/grafana.ini
  #     - grafana_data:/var/lib/grafana
  #   networks:
  #     - app-tier

volumes:
  redis-data:
  rabbitmq_data:
  postgres_data:
  # prom_data:
  # grafana_data:
  # loki_data:
  redis-insight-data: