import Head from "next/head";
import { Work_Sans, Bebas_Neue, Karla } from "next/font/google";
const karla = Karla({
  subsets: ["latin"],
  variable: "--font-karla",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});
import Inner from "@/components/Layout/Inner";
import HomeIndex from "./_components";
export default function Home() {
  return (
    <div className={`${karla.variable}`}>
      <Head>
        <title>Homes & Villas by Okeke Benneth | Book directly and save </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://hopper.com/favicon.ico" />
      </Head>
      <Inner>
        <HomeIndex />
      </Inner>
    </div>
  );
}
