{
 "title": "Auth Service Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Login Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(user_http_request_total{route=\"/login\",success=\"false\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Login Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(user_http_request_duration_seconds_bucket{route=\"/login\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time for Login",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "user_http_request_duration_seconds_bucket{route=\"/login\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Authentication Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "user_http_request_total{route=\"/login\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}