apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
  namespace: booking-platform
type: Opaque
stringData:
  POSTGRES_USER: booking
  POSTGRES_PASSWORD: booking-pass
  REDIS_PASSWORD: redis-pass
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  ELASTICSEARCH_PASSWORD: elastic-pass
  JWT_SECRET: change-me
  API_KEY: change-me
