#Please copy or rename this file to secret-shared.yaml
#Ensure the secret-shared.yaml file is not tracked by git
#Add it to .gitignore to prevent leaks

apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
  namespace: booking-platform
type: Opaque
stringData:
  NODE_ENV: "example"
  PORT: "text here"
  API_INTERNAL_URL: "text here"

  POSTGRES_USER: "text here"
  POSTGRES_PASSWORD: "text here"
  POSTGRES_DB: "example"
  DATABASE_URL: "example"

  REDIS_HOST: "text here"
  REDIS_PORT: "example"
  REDIS_PASSWORD: "text here"

  RABBITMQ_URL: "text here"
# RABBITMQ_DEFAULT_USER: guest
# RABBITMQ_DEFAULT_PASS: guest

  ELASTICSEARCH_URL: "text here"
  ELASTICSEARCH_USERNAME: "example"
  ELASTICSEARCH_PASSWORD: "text here"

  JWT_SECRET: "example"
# API_KEY: change-me

  CLOUDINARY_CLOUD_NAME: "text here"
  CLOUDINARY_API_KEY: "text here"
  CLOUDINARY_API_SECRET: "example"

  PGA_API_KEY: "text here"

  PAYSTACK_SECRET_KEY: "text here"
  PAYSTACK_WEBHOOK_SECRET: "text here"

# App
  WEB_ORIGIN: "text here
  BASE_DOMAIN=example"

# OTel
  OTEL_SERVICE_NAME: "example"
  OTEL_ENABLED: "true"
  TEMPO_URL: "text here"

# Grafana
  GRAFANA_ADMIN_USER: "text here"
  GRAFANA_ADMIN_PASSWORD: "example"

# Outbox
  OUTBOX_POLL_INTERVAL_MS: "example"
  INTERNAL_SECRET: "text here"

  RESEND_API_KEY: "text here"
  EMAIL_FROM: "text here"
  EMAIL_FROM_NAME: "text here"
  EMAIL_PROVIDER: "text here"


