apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-exporter-service
  namespace: booking-platform
spec:
  selector:
    app: pgbouncer-exporter
  ports:
    - port: 9127
      targetPort: 9127
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-exporter
  namespace: booking-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer-exporter
  template:
    metadata:
      labels:
        app: pgbouncer-exporter
    spec:
      containers:
        - name: pgbouncer-exporter
          image: spreaker/prometheus-pgbouncer-exporter:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: PGBOUNCER_HOST
              value: pgbouncer

            - name: PGBOUNCER_PORT
              value: "6432"

            - name: PGBOUNCER_USER
              value: postgres

            - name: PGBOUNCER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: POSTGRES_PASSWORD

          ports:
            - containerPort: 9127

          resources:
            requests:
              cpu: 80m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
