apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram-ops
    receivers:
      - uid: telegram-ops
        type: telegram
        disableResolveMessage: false
        settings:
          bottoken: "$__env{TELEGRAM_BOT_TOKEN}"
          chatid: "8894235638"