[global]
repo1-type=s3
repo1-s3-bucket=booking-pg-backups-463d5e40
repo1-s3-region=us-east-2
repo1-s3-endpoint=s3.us-east-2.amazonaws.com
repo1-path=/pgbackrest

repo1-retention-full=2
repo1-retention-full-type=count

compress-type=zst
compress-level=3

process-max=2
log-level-console=info
log-level-file=detail

[booking-primary]
pg1-path=/var/lib/postgresql/data
pg1-port=5432