import Head from "next/head";
import { Work_Sans, Bebas_Neue, Karla } from "next/font/google";
import DashboardIndex from "./_components";
import DashboardLayout from "./layout";
const karla = Karla({
  subsets: ["latin"],
  variable: "--font-karla",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});
export default function Home() {
  return (
    <div className={`${karla.variable}`}>
      <Head>
        <title>
          Dashboard || Homes & Villas
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://hopper.com/favicon.ico" />
      </Head>
     {/* <DashboardLayout>
      <DashboardIndex/>
     </DashboardLayout> */}

       <DashboardIndex/>
    </div>
  );
}
